HMWeb.Core/Models/ErrorViewModel.cs
using System;

namespace HMWeb.Core.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HMWeb.Core/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HMWeb.Core.Models;

namespace HMWeb.Core.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HMWeb.Core/Controllers/MaquinariasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HMWeb.Biblioteca.Modelos;

namespace HMWeb.Core.Controllers
{
    
    public class MaquinariasController : Controller
    {
        private readonly HMContext _context;

        public MaquinariasController(HMContext context)
        {
            _context = context;
        }

        // GET: Maquinarias
        public async Task<IActionResult> Index()
        {
            ViewData["IdCentro"] = new SelectList(_context.Centros, "IdCentro", "Nombre");
            ViewData["IdEmpresa"] = new SelectList(_context.Empresas, "IdEmpresa", "IdEmpresa");
            ViewData["IdServicio"] = new SelectList(_context.Servicios, "IdServicio", "IdServicio");
            IEnumerable<Maquinarias> hMContext = await _context.Maquinarias.Include(m => m.IdCentroNavigation).Include(m => m.IdEmpresaNavigation).Include(m => m.IdServicioNavigation).ToListAsync();                             

            return View(hMContext);
        }

        // GET: Maquinarias/Details/5
        public async Task<IActionResult> _Details(int? id)
        
        {
            if (id == null)
            {
                return NotFound();
            }

            var maquinarias = await _context.Maquinarias
                .Include(m =>  m.IdCentroNavigation)
                .Include(m => m.IdEmpresaNavigation)
                .Include(m => m.IdServicioNavigation)
                .FirstOrDefaultAsync(m => m.IdMaquinaria == id);
            if (maquinarias == null)
            {
                return NotFound();
            }

            return PartialView("_Details", maquinarias);
        }

        // GET: Maquinarias/Create
        public IActionResult _Create()
        {
            ViewData["IdCentro"] = new SelectList(_context.Centros, "IdCentro", "Nombre");
            ViewData["IdEmpresa"] = new SelectList(_context.Empresas, "IdEmpresa", "IdEmpresa");
            ViewData["IdServicio"] = new SelectList(_context.Servicios, "IdServicio", "IdServicio");
            return PartialView("_Create");
        }

        // POST: Maquinarias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> _Create([Bind("IdMaquinaria,IdEmpresa,IdCentro,IdServicio,NumeroSerie,Matricula,FechaAlta,FechaBaja,Activa,UltimaLecturaKms,UltimaLecturaHoras,IndicaKH")] Maquinarias maquinarias)
        {
            if (ModelState.IsValid)
            {
                _context.Add(maquinarias);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCentro"] = new SelectList(_context.Centros, "IdCentro", "Nombre", maquinarias.IdCentro);
            ViewData["IdEmpresa"] = new SelectList(_context.Empresas, "IdEmpresa", "IdEmpresa", maquinarias.IdEmpresa);
            ViewData["IdServicio"] = new SelectList(_context.Servicios, "IdServicio", "IdServicio", maquinarias.IdServicio);
            return RedirectToAction("Index");
        }

       
        // GET: Maquinarias/Edit/5
        public async Task<IActionResult> _Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var maquinarias = await _context.Maquinarias.FindAsync(id);
            
            if (maquinarias == null)
            {
                return NotFound();
            }
            ViewData["IdCentro"] = new SelectList(_context.Centros, "IdCentro", "Nombre", maquinarias.IdCentro);
            ViewData["IdEmpresa"] = new SelectList(_context.Empresas, "IdEmpresa", "IdEmpresa", maquinarias.IdEmpresa);
            ViewData["IdServicio"] = new SelectList(_context.Servicios, "IdServicio", "IdServicio", maquinarias.IdServicio);
            return PartialView("_Edit", maquinarias);
        }

        // POST: Maquinarias/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> _Edit(int id, [Bind("IdMaquinaria,IdEmpresa,IdCentro,IdServicio,NumeroSerie,Matricula,FechaAlta,FechaBaja,Activa,UltimaLecturaKms,UltimaLecturaHoras,IndicaKH")] Maquinarias maquinarias)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(maquinarias);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MaquinariasExists(maquinarias.IdMaquinaria))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCentro"] = new SelectList(_context.Centros, "IdCentro", "Nombre", maquinarias.IdCentro);
            ViewData["IdEmpresa"] = new SelectList(_context.Empresas, "IdEmpresa", "IdEmpresa", maquinarias.IdEmpresa);
            ViewData["IdServicio"] = new SelectList(_context.Servicios, "IdServicio", "IdServicio", maquinarias.IdServicio);
            return RedirectToAction("Index");
        }

        // GET: Maquinarias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var maquinarias = await _context.Maquinarias
                .Include(m => m.IdCentroNavigation)
                .Include(m => m.IdEmpresaNavigation)
                .Include(m => m.IdServicioNavigation)
                .FirstOrDefaultAsync(m => m.IdMaquinaria == id);
            if (maquinarias == null)
            {
                return NotFound();
            }

            return View( maquinarias);
        }
 
        // POST: Maquinarias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var maquinarias = await _context.Maquinarias.FindAsync(id);
            _context.Maquinarias.Remove(maquinarias);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MaquinariasExists(int id)
        {
            return _context.Maquinarias.Any(e => e.IdMaquinaria == id);
        }
    }
}

HMWeb.Core/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido</h1>
    <img class="img-fluid" src="~/img/iXNet.png"/>
</div>

HMWeb.Core/Views/Indexcopi.cshtml
@model IEnumerable<HMWeb.Biblioteca.Modelos.Maquinarias>

@{
    ViewData["Title"] = "Index";
}

<h1 class="alert-info">Listado de Maquinarias</h1>

<p>
    <a asp-action="Create">Crear nueva maquinaria</a>
</p>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumeroSerie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Matricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaAlta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaBaja)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Activa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UltimaLecturaKms)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UltimaLecturaHoras)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IndicaKH)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.IdCentroNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdEmpresaNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdServicioNavigation)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroSerie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Matricula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaAlta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaBaja)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Activa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UltimaLecturaKms)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UltimaLecturaHoras)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IndicaKH)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.IdCentroNavigation.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdEmpresaNavigation.IdEmpresa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdServicioNavigation.IdServicio)
            </td>*@
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdMaquinaria">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.IdMaquinaria">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.IdMaquinaria">Borrar</a>
            </td>
        </tr>
}
    </tbody>
</table>

HMWeb.Core/Views/Maquinarias/Delete.cshtml
@model HMWeb.Biblioteca.Modelos.Maquinarias


<h3>¿Seguro que desea borrar este item?</h3>
<div>
    <dl class="row">
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.NumeroSerie)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.NumeroSerie)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.Matricula)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.FechaAlta)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.FechaAlta)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.FechaBaja)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.FechaBaja)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Activa)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.Activa)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.UltimaLecturaKms)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.UltimaLecturaKms)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.UltimaLecturaHoras)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.UltimaLecturaHoras)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.IndicaKH)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.IndicaKH)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.IdCentroNavigation)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.IdCentroNavigation.Nombre)
        </dd class>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.IdEmpresaNavigation)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.IdEmpresaNavigation.IdEmpresa)
        </dd class>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.IdServicioNavigation)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.IdServicioNavigation.IdServicio)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdMaquinaria" />
        <input type="submit" data-id="IdMaquinaria" value="Borrar" class="btn btn-danger" /> 
    </form>
</div>

HMWeb.Core/Views/Maquinarias/Details.cshtml
@model HMWeb.Biblioteca.Modelos.Maquinarias

@{
    ViewData["Title"] = "Details";
}

<h1 class="alert-info">Detalles</h1>

<div>
    <h4>Maquinarias</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroSerie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroSerie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Matricula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaAlta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaAlta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaBaja)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaBaja)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Activa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Activa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UltimaLecturaKms)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UltimaLecturaKms)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UltimaLecturaHoras)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UltimaLecturaHoras)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IndicaKH)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IndicaKH)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCentroNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCentroNavigation.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdEmpresaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdEmpresaNavigation.IdEmpresa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdServicioNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdServicioNavigation.IdServicio)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdMaquinaria">Editar</a> |
    <a asp-action="Index">Retorno al listado</a>
</div>

HMWeb.Core/Views/Maquinarias/Index.cshtml
@model IEnumerable<HMWeb.Biblioteca.Modelos.Maquinarias>

@{
    ViewData["Title"] = "Index";

}

<h1 class="alert-info">Listado de Maquinarias</h1>
<div class="float-left">
    <button class="btn btn-info" onclick="CreateMaquinaria()">Crear nueva maquinaria</button>
</div>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumeroSerie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Matricula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaAlta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaBaja)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Activa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UltimaLecturaKms)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UltimaLecturaHoras)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IndicaKH)
            </th>
            <th style="display:none">
                @Html.DisplayNameFor(model => model.IdEmpresa)
            </th>
            <th style="display:none">
                @Html.DisplayNameFor(model => model.IdCentro)
            </th>
            <th style="display:none">
                @Html.DisplayNameFor(model => model.IdServicio)
            </th>

            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>

    <tbody id="tableFilas">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NumeroSerie)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Matricula)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaAlta)
                  
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaBaja)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Activa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UltimaLecturaKms)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UltimaLecturaHoras)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IndicaKH)
                </td>
                <td style="display:none">
                    @Html.DisplayFor(modelItem => item.IdEmpresa)
                </td>
                <td style="display:none">
                    @Html.DisplayFor(modelItem => item.IdCentro)
                </td>
                <td style="display:none">
                    @Html.DisplayFor(modelItem => item.IdServicio)
                </td>
                <td class="col-sm-4"><button class="btn btn-info"  onclick="EditMaquinaria(@item.IdMaquinaria)" data-toggle="modal" data-target="#editModal">Editar </button> </td>
                <td class="col-sm-4"><button class="btn btn-info" onclick="DetallesMaquinaria(@item.IdMaquinaria)" data-toggle="modal" data-target="#editModal">Detalles</button> </td>
                <td class="col-sm-4"><a class="btn btn-info" asp-controller="Maquinarias" asp-action="Delete" asp-route-id="@item.IdMaquinaria"> Borrar </a> </td>


            </tr>

        }
    </tbody>

</table>


<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="modalDiv" class="modal-body">


            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>

            </div>
        </div>
    </div>
</div>


@section Scripts{

    <script>
        var CreateMaquinaria = function () {
            var url = "/Maquinarias/_Create";
            $("#modalDiv").load(url, function () {
                $("#editModal").modal("show");
            })
        }
    </script>
    <script>
        var EditMaquinaria = function (item) {
            var url = "/Maquinarias/_Edit?id=" + parseInt(item);
            $("#modalDiv").load(url, function () {
                $("#editModal").modal("show");
            })
        }
    </script>
    <script>
        var DetallesMaquinaria = function (item) {
            var url = "/Maquinarias/_Details?id=" + parseInt(item);
            $("#modalDiv").load(url, function () {
                $("#editModal").modal("show");
            })
        }
    </script>



    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

HMWeb.Core/Views/Maquinarias/_Create.cshtml
@model HMWeb.Biblioteca.Modelos.Maquinarias

<h4>Crear nueva maquinaria</h4>
<div class="row">
    <div class="table-responsive-sm container-fluid">
        <form asp-action="_Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdEmpresa" class="control-label"></label>
                <select asp-for="IdEmpresa" class ="form-control" asp-items="ViewBag.IdEmpresa"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdCentro" class="control-label"></label>
                <select asp-for="IdCentro" class ="form-control" asp-items="ViewBag.IdCentro"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdServicio" class="control-label"></label>
                <select asp-for="IdServicio" class ="form-control" asp-items="ViewBag.IdServicio"></select>
            </div>
            <div class="form-group">
                <label asp-for="NumeroSerie" class="control-label"></label>
                <input asp-for="NumeroSerie" class="form-control" />
                <span asp-validation-for="NumeroSerie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Matricula" class="control-label"></label>
                <input asp-for="Matricula" class="form-control" />
                <span asp-validation-for="Matricula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaAlta" class="control-label"></label>
                <input asp-for="FechaAlta" class="form-control" />
                <span asp-validation-for="FechaAlta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaBaja" class="control-label"></label>
                <input asp-for="FechaBaja" class="form-control" />
                <span asp-validation-for="FechaBaja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Activa" class="control-label"></label>
                <input asp-for="Activa" class="form-control" />
                <span asp-validation-for="Activa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UltimaLecturaKms" class="control-label"></label>
                <input asp-for="UltimaLecturaKms" class="form-control" />
                <span asp-validation-for="UltimaLecturaKms" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UltimaLecturaHoras" class="control-label"></label>
                <input asp-for="UltimaLecturaHoras" class="form-control" />
                <span asp-validation-for="UltimaLecturaHoras" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IndicaKH" class="control-label"></label>
                <input asp-for="IndicaKH" class="form-control" />
                <span asp-validation-for="IndicaKH" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HMWeb.Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HM Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HM Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Maquinarias" asp-action="Index">Maquinarias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - HM Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>